# Generated by Django 6.0.5 on 2026-05-31 06:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_profile_github_starred_repos_import_enabled_and_more"),
        ("repos", "0015_repositorylike"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStarredRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starred_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_repository_links",
                        to="core.profile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_by_profiles",
                        to="repos.repository",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("starred_at"), descending=True, nulls_last=True),
                    "repository__full_name",
                ],
                "indexes": [
                    models.Index(
                        fields=["profile", "-last_seen_at"], name="repos_users_profile_e4b79f_idx"
                    ),
                    models.Index(
                        fields=["repository", "-last_synced_at"],
                        name="repos_users_reposit_8ad0da_idx",
                    ),
                ],
                "unique_together": {("profile", "repository")},
            },
        ),
    ]
