# Generated by Django 6.0.5 on 2026-06-01 09:03

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0018_merge_repository_tag_backfill_and_starred_import"),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='dependency_ecosystems',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='dependency_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='detected_stacks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='package_managers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='stack_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='stack_detection_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='stack_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=django.contrib.postgres.indexes.GinIndex(fields=['dependency_ecosystems'], name='repo_dep_ecosystems_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=django.contrib.postgres.indexes.GinIndex(fields=['package_managers'], name='repo_package_mgrs_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=django.contrib.postgres.indexes.GinIndex(fields=['detected_stacks'], name='repo_detected_stacks_gin_idx'),
        ),
    ]
