# Generated by Django 6.0.5 on 2026-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repos", "0022_repository_snapshot_growth_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["-created_at", "-id"], name="repo_created_desc_idx"),
        ),
    ]
