# Generated by Django 6.0.5 on 2026-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailsent_email_type_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_starred_repos_import_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_starred_repos_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_starred_repos_last_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
