# Generated by Django 6.0.5 on 2026-07-04 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_blogpo_status_c0e87f_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_blogpo_slug_361555_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_blogpo_templat_8f2ca6_idx",
        ),
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blog_blogpo_target__294030_idx",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.DeleteModel(
            name="BlogCategory",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.DeleteModel(
            name="BlogTag",
        ),
    ]
